FROM n8nio/n8n

EXPOSE 5678

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=StrongPassword123
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV TZ=UTC
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

CMD ["n8n", "start"]
